<a href="https://colab.research.google.com/github/jwangui52-web/CDAV/blob/main/Pandas_Walkthrough_Day1to3_with_outputs_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# pandas, start to finish — a guided walkthrough
### Days 1 to 3, all in one place

We are going to take **one messy dataset** and clean it together, from the moment it
lands on our desk to the moment it is ready to analyse. Every step you have learned
this week appears here in order.

**How to use this notebook:** run one cell at a time. Read the note above each cell,
predict what will happen, *then* run it. If a cell errors, read the **last line** of the
error first — that is the real problem.

The dataset is `kenya_transactions_messy.csv`: 1000 rows of (deliberately messy)
Kenyan sales transactions. It has every problem a real dataset throws at you.

---
## 0. Setup

Two imports, every notebook, forever. `pd` for pandas, `np` for numpy.

In [ ]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)   # show every column

Load the file. If you are in Colab, upload `kenya_transactions_messy.csv` first
(folder icon on the left), or paste a raw GitHub link in place of the filename.

In [ ]:
df = pd.read_csv('kenya_transactions_messy.csv')
df.head()

,Txn ID,Full Name,County,Amount Paid,Txn Date,Paid Date,Rainfall mm,Status
0,TXN00729,"Wanjiku, Jane",NAIROBI,76,22/02/2026,12/03/2026,222.9,?
1,TXN00798,"Onyango, Victor",Kisumu,-,03/06/2026,NaN,902.6,P
2,TXN00672,"Muthoni, John",Kiambu,6920,26/04/2026,11/05/2026,1122.0,P
3,TXN00660,"Barasa, David",Kajiado,4342,21/02/2026,05/03/2026,509.3,P
4,TXN00830,"Kimani, Michael",Kisumu,452,11/03/2026,10/04/2026,1193.9,P

Notice already: some column names have **spaces**, the amounts have **commas and “KES”**,
and the county names are spelled several different ways. That is normal. We will fix all of it.

---
## 1. First look  *(Day 1)*

Before touching anything, always run the same five checks. This is a habit, not a chore —
you never analyse data you have not looked at.

**How big is it?**

In [ ]:
df.shape        # (rows, columns)

(1000, 8)

**The first and last few rows.** Always check the tail too — junk rows love to hide at the bottom.

In [ ]:
df.head()

,Txn ID,Full Name,County,Amount Paid,Txn Date,Paid Date,Rainfall mm,Status
0,TXN00729,"Wanjiku, Jane",NAIROBI,76,22/02/2026,12/03/2026,222.9,?
1,TXN00798,"Onyango, Victor",Kisumu,-,03/06/2026,NaN,902.6,P
2,TXN00672,"Muthoni, John",Kiambu,6920,26/04/2026,11/05/2026,1122.0,P
3,TXN00660,"Barasa, David",Kajiado,4342,21/02/2026,05/03/2026,509.3,P
4,TXN00830,"Kimani, Michael",Kisumu,452,11/03/2026,10/04/2026,1193.9,P

In [ ]:
df.tail()

,Txn ID,Full Name,County,Amount Paid,Txn Date,Paid Date,Rainfall mm,Status
995,TXN00248,"Rotich, Stephen",Nairobi,11105,06/06/2026,18/06/2026,896.8,NaN
996,TXN00314,"Auma, Samuel",Mombasa,17377,17/01/2026,NaN,639.9,P
997,TXN00225,"Barasa, David",Kisumu,153,05/04/2026,18/04/2026,1208.0,U
998,TXN00712,"Cheruiyot, Jane",Kericho,4862,09/02/2026,14/02/2026,1636.0,NaN
999,TXN00074,"Nyongesa, Joyce",Nairobi,1021,05/02/2026,15/02/2026,NaN,P

**The single most useful command in pandas.** `info()` tells you three things at once:
how big, what type each column is, and where values are missing.

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Txn ID         1000 non-null   str
 1   Full Name      1000 non-null   str
 2   County         993 non-null    str
 3    Amount Paid   960 non-null    str
 4   Txn Date       1000 non-null   str
 5   Paid Date      849 non-null    str
 6   Rainfall mm    963 non-null    float64
 7   Status         879 non-null    str
dtypes: float64(1), str(7)
memory usage: 62.6 KB

Look carefully at that output:
- `Rainfall mm` has fewer non-null values than the others → **missing data**.
- ` Amount Paid ` is `object` → it is **text**, not a number. We cannot do maths on it yet.

**The summary numbers** for any column that is already numeric:

In [ ]:
df.describe()

       Rainfall mm
count   963.000000
mean    956.926376
std     439.099355
min     180.800000
25%     585.650000
50%     952.400000
75%    1316.050000
max    1747.800000

**The type of every column.** Get used to running this before you trust a single number.

In [ ]:
df.dtypes

Txn ID               str
Full Name            str
County               str
 Amount Paid         str
Txn Date             str
Paid Date            str
Rainfall mm      float64
Status               str
dtype: object

### Selecting columns

One pair of brackets gives you a single column (a **Series**).

In [ ]:
df['Rainfall mm'].head()

0     222.9
1     902.6
2    1122.0
3     509.3
4    1193.9
Name: Rainfall mm, dtype: float64

Two pairs — a **list** of names inside the brackets — gives you a smaller table (a **DataFrame**).

In [ ]:
df[['Txn ID', 'Rainfall mm']].head()

     Txn ID  Rainfall mm
0  TXN00729        222.9
1  TXN00798        902.6
2  TXN00672       1122.0
3  TXN00660        509.3
4  TXN00830       1193.9

### loc and iloc

`iloc` selects by **position** (counting from 0). `loc` selects by **label**.
Remember: **i** for integer, **l** for label.

In [ ]:
df.iloc[0]        # the first row, by position

Txn ID                 TXN00729
Full Name        Wanjiku,  Jane
County                  NAIROBI
 Amount Paid                 76
Txn Date             22/02/2026
Paid Date            12/03/2026
Rainfall mm               222.9
Status                        ?
Name: 0, dtype: object

In [ ]:
df.loc[0]         # the row labelled 0

Txn ID                 TXN00729
Full Name        Wanjiku,  Jane
County                  NAIROBI
 Amount Paid                 76
Txn Date             22/02/2026
Paid Date            12/03/2026
Rainfall mm               222.9
Status                        ?
Name: 0, dtype: object

> **Your turn:** show just the first 3 rows of the `Status` column. Try it before moving on.

In [ ]:
# your turn:

---
## 2. Filtering  *(Day 2)*

Nobody analyses 1000 rows. They analyse the rows that matter. Filtering is how you
keep only those. It happens in two steps: **ask a question**, then **use the answer**.

**Step 1 — ask a question.** A comparison makes a column of True/False, one per row.
This is called a *boolean mask*.

In [ ]:
df['Rainfall mm'] > 1000

0      False
1      False
2       True
3      False
4       True
       ...
995    False
996    False
997     True
998     True
999    False
Name: Rainfall mm, Length: 1000, dtype: bool

**Step 2 — use the mask** to keep only the True rows.

In [ ]:
df[df['Rainfall mm'] > 1000].head()

,Txn ID,Full Name,County,Amount Paid,Txn Date,Paid Date,Rainfall mm,Status
2,TXN00672,"Muthoni, John",Kiambu,6920,26/04/2026,11/05/2026,1122.0,P
4,TXN00830,"Kimani, Michael",Kisumu,452,11/03/2026,10/04/2026,1193.9,P
7,TXN00750,"Wafula, Mercy",Nakuru,-260,28/01/2026,05/02/2026,1334.8,?
9,TXN00477,"Njoroge, George",Eldoret,560 KES,17/01/2026,20/01/2026,1106.8,P
10,TXN00478,"Kimani, Felix",Meru,947,01/02/2026,03/03/2026,1667.4,?

**Two conditions at once.** Use `&` for *and*, `|` for *or*.
Every condition needs its **own brackets** — this is the number-one beginner error.

In [ ]:
df[(df['Rainfall mm'] > 1000) & (df['Status'] == 'P')].head()

,Txn ID,Full Name,County,Amount Paid,Txn Date,Paid Date,Rainfall mm,Status
2,TXN00672,"Muthoni, John",Kiambu,6920,26/04/2026,11/05/2026,1122.0,P
4,TXN00830,"Kimani, Michael",Kisumu,452,11/03/2026,10/04/2026,1193.9,P
9,TXN00477,"Njoroge, George",Eldoret,560 KES,17/01/2026,20/01/2026,1106.8,P
11,TXN00617,"Wafula, Kevin",Nairobi,681,05/01/2026,21/01/2026,1174.3,P
18,TXN00216,"Njoroge, George",Nairobi,609,15/04/2026,03/05/2026,1258.8,P

**Before filtering a text column, see what is actually in it.** `value_counts()` lists every
value and how often it appears.

In [ ]:
df['County '].value_counts()

County
Mombasa      119
Nairobi      101
Kisumu        81
Nakuru        65
Kiambu        57
Eldoret       57
Machakos      45
Meru          43
NAIROBI       40
Kakamega      38
nairobi       35
Nyeri         35
Kajiado       33
Kilifi        30
 Nairobi      26
Kitale        25
Kericho       22
Bungoma       22
Nairobi​      18
Nakuru        10
Kisumu         9
Mombasa        8
Eldoret        7
Nyeri          6
ELDORET        5
Kiambu         5
Kajiado        5
Kakamega       4
Machakos       4
MOMBASA        4
KERICHO        4
Kericho        3
KISUMU         3
BUNGOMA        3
Kitale         3
Meru           3
Kilifi         3
NYERI          2
KIAMBU         2
Bungoma        2
KILIFI         2
KAJIADO        2
MACHAKOS       1
NAKURU         1
Name: count, dtype: int64

Look at that result. **Nairobi is spelled several different ways** — `Nairobi`, `nairobi`,
`NAIROBI`, and one with a space. To pandas these are *different counties*. If we counted
sales per county right now, Nairobi would be split four ways and every answer would be wrong.

We will fix this in the cleaning section. For now, just notice the problem is real and silent.

---
## 3. Cleaning  *(Day 2 — the heart of the week)*

This is what “data cleaning” actually means: taking a broken table and making every column
say what it is supposed to say. We do it in a set order.

### 3a. Fix the column names first

Names with spaces and capitals are a trap — ` Amount Paid ` will cause a `KeyError` you
cannot see. Clean them all in one line, so everything after this is easy to type.

In [ ]:
df.columns          # the messy names, before

Index(['Txn ID', 'Full Name', 'County ', ' Amount Paid ', 'Txn Date',
       'Paid Date', 'Rainfall mm', 'Status'],
      dtype='str')

In [ ]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
df = df.rename(columns={'amount_paid': 'amount'})
df.columns          # clean names, after

Index(['txn_id', 'full_name', 'county', 'amount', 'txn_date', 'paid_date',
       'rainfall_mm', 'status'],
      dtype='str')

From here on we can type `df['amount']` and `df['county']` — no spaces, no surprises.

### 3b. Find the missing values

`isna().sum()` counts the gaps in every column. Add this to your first-look habit.

In [ ]:
df.isna().sum()

txn_id           0
full_name        0
county           7
amount          40
txn_date         0
paid_date      151
rainfall_mm     37
status         121
dtype: int64

### 3c. Find duplicate rows

How many rows are exact repeats?

In [ ]:
df.duplicated().sum()

np.int64(40)

And how many **distinct transaction IDs** are there, versus total rows? If these differ,
some IDs appear more than once.

In [ ]:
print('rows:', len(df))
print('distinct txn_id:', df['txn_id'].nunique())

rows: 1000
distinct txn_id: 945

We will remove duplicates later, once the rest is clean — so we only decide once.

### 3d. Rescue the amount column

`amount` came in as **text** because some values have commas or “KES”. Look:

In [ ]:
df['amount'].head(10)

0         76
1          -
2       6920
3       4342
4        452
5       -207
6        829
7       -260
8        402
9    560 KES
Name: amount, dtype: str

The fix is always **strip the junk first, then convert**. `errors='coerce'` turns anything
it cannot read (like `-` or `NA`) into `NaN`, which we already know how to handle.

In [ ]:
clean = (df['amount'].astype(str)
                     .str.replace(',', '', regex=False)
                     .str.replace(' KES', '', regex=False)
                     .str.strip())
df['amount'] = pd.to_numeric(clean, errors='coerce')
df['amount'].dtype        # now a real number

dtype('float64')

How many values could not be converted (they became `NaN`)?

In [ ]:
df['amount'].isna().sum()

np.int64(60)

Some amounts are **negative**, which is impossible for a sale. Set those to missing — we do
not know the true value, so we should not guess it. This is the correct way to change part of
a table: `df.loc[condition, column] = value`.

In [ ]:
print('negative amounts:', (df['amount'] < 0).sum())
df.loc[df['amount'] < 0, 'amount'] = np.nan

negative amounts: 56

Now that `amount` is numeric, it finally appears in `describe()` — it was invisible before.

In [ ]:
df['amount'].describe()

count      884.000000
mean      3192.366516
std       4593.505857
min         51.000000
25%        496.750000
50%        905.000000
75%       3765.500000
max      19936.000000
Name: amount, dtype: float64

---
## 4. Cleaning text  *(Day 3)*

Now we kill the four Nairobis.

The `.str` accessor applies a text method to **every row at once**. Chain the fixes:
remove the sneaky hidden character, strip the spaces, then Title-Case everything.

In [ ]:
df['county'] = (df['county'].str.replace('\u200b', '', regex=False)  # a hidden 'zero-width' space
                            .str.strip()
                            .str.title())
df['county'].value_counts()

county
Nairobi     220
Mombasa     131
Kisumu       93
Nakuru       76
Eldoret      69
Kiambu       64
Machakos     50
Meru         46
Nyeri        43
Kakamega     42
Kajiado      40
Kilifi       35
Kericho      29
Kitale       28
Bungoma      27
Name: count, dtype: int64

**One line, and the four Nairobis became one.** Every count and chart from here on will be correct.

### Split a column into two

`full_name` is `“Surname, First”`. Split it on the comma into two real columns.

In [ ]:
df['full_name'].head()

0     Wanjiku,  Jane
1    Onyango, Victor
2      Muthoni, John
3     Barasa,  David
4    Kimani, Michael
Name: full_name, dtype: str

In [ ]:
parts = df['full_name'].str.split(',', expand=True)
df['surname']    = parts[0].str.strip()
df['first_name'] = parts[1].str.strip()
df[['surname', 'first_name']].head()

   surname first_name
0  Wanjiku       Jane
1  Onyango     Victor
2  Muthoni       John
3   Barasa      David
4   Kimani    Michael

---
## 5. Dates  *(Day 3)*

Right now the dates are just **text** — you cannot sort them properly or do arithmetic.

In [ ]:
df['txn_date'].dtype        # object = text

Convert to real dates. These are **DD/MM/YYYY** (Kenyan style), so we must say `dayfirst=True`
or pandas reads the day as the month. Bad dates become `NaT` (the date version of `NaN`).

In [ ]:
df['txn_date']  = pd.to_datetime(df['txn_date'],  dayfirst=True, errors='coerce')
df['paid_date'] = pd.to_datetime(df['paid_date'], dayfirst=True, errors='coerce')
df['txn_date'].dtype        # now a real date

dtype('<M8[us]')

Now we can pull the pieces out with `.dt`, just like `.str` for text.

In [ ]:
df['month']   = df['txn_date'].dt.month_name()
df['weekday'] = df['txn_date'].dt.day_name()
df[['txn_date', 'month', 'weekday']].head()

    txn_date     month    weekday
0 2026-02-22  February     Sunday
1 2026-06-03      June  Wednesday
2 2026-04-26     April     Sunday
3 2026-02-21  February   Saturday
4 2026-03-11     March  Wednesday

And do **date arithmetic** — how many days did customers take to pay?

In [ ]:
df['days_to_pay'] = (df['paid_date'] - df['txn_date']).dt.days
df['days_to_pay'].describe()

count    849.000000
mean      14.261484
std        8.788792
min        0.000000
25%        7.000000
50%       14.000000
75%       21.000000
max       30.000000
Name: days_to_pay, dtype: float64

---
## 6. Building new columns  *(Day 3)*

Most new columns are just maths or a comparison — no fancy tools needed.

In [ ]:
df['is_large'] = df['amount'] > 1000                     # a True/False flag

In [ ]:
df['size'] = np.where(df['amount'] > 1000, 'big', 'small')  # two outcomes

Tidy the status codes into readable words. `replace` swaps values; mapping `'?'` to `None`
turns the unknowns into proper missing values.

In [ ]:
df['status'] = df['status'].replace({'P': 'paid', 'U': 'unpaid', '?': np.nan})
df['status'].value_counts(dropna=False)

status
paid      438
unpaid    295
NaN       267
Name: count, dtype: int64

---
## 7. Duplicates and missing values — the decisions  *(Day 2)*

We saved these for last, so we decide once, on clean data.

**Duplicates:** a repeated `txn_id` is a genuine duplicate here, so keep the first of each.

In [ ]:
before = len(df)
df = df.drop_duplicates(subset=['txn_id']).copy()
print('removed', before - len(df), 'duplicate rows')

removed 55 duplicate rows

**Missing values — a judgement call, not a rule.** Here we:
- **drop** rows with no `amount` (we cannot analyse a sale with no value), and
- **fill** missing rainfall with the median (a sensible, honest default).

The important part is that we can *explain* each choice — that is the graded skill.

In [ ]:
df = df.dropna(subset=['amount'])
df['rainfall_mm'] = df['rainfall_mm'].fillna(df['rainfall_mm'].median())
df.isna().sum()

txn_id           0
full_name        0
county           6
amount           0
txn_date         5
paid_date      131
rainfall_mm      0
status         217
surname          0
first_name       0
month            5
weekday          5
days_to_pay    131
is_large         0
size             0
dtype: int64

> **Write it down.** In a real project you would add a note like:
> *“Dropped rows with missing amount (cannot value the sale); filled missing rainfall with the
> median; removed duplicate transaction IDs.”* The code is not enough on its own.

---
## 8. Check, then save  *(Day 2)*

Never trust that cleaning worked — verify it. Re-run `info()`: right types, no unexpected gaps.

In [ ]:
df.info()

<class 'pandas.DataFrame'>
Index: 834 entries, 0 to 999
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   txn_id       834 non-null    str
 1   full_name    834 non-null    str
 2   county       828 non-null    str
 3   amount       834 non-null    float64
 4   txn_date     829 non-null    datetime64[us]
 5   paid_date    703 non-null    datetime64[us]
 6   rainfall_mm  834 non-null    float64
 7   status       617 non-null    str
 8   surname      834 non-null    str
 9   first_name   834 non-null    str
 10  month        829 non-null    str
 11  weekday      829 non-null    str
 12  days_to_pay  703 non-null    float64
 13  is_large     834 non-null    bool
 14  size         834 non-null    str
dtypes: bool(1), datetime64[us](2), float64(3), str(9)
memory usage: 98.5 KB

Save the clean data to a **new** file. `index=False` stops pandas adding a junk column.
Never overwrite the raw file.

In [ ]:
df.to_csv('kenya_transactions_clean.csv', index=False)
print('saved:', df.shape)

saved: (834, 15)

Load it back to prove it is really there and really clean.

In [ ]:
check = pd.read_csv('kenya_transactions_clean.csv')
check.head()

,txn_id,full_name,county,amount,txn_date,paid_date,rainfall_mm,status,surname,first_name,month,weekday,days_to_pay,is_large,size
0,TXN00729,"Wanjiku, Jane",Nairobi,76.0,2026-02-22,2026-03-12,222.9,NaN,Wanjiku,Jane,February,Sunday,18.0,False,small
1,TXN00672,"Muthoni, John",Kiambu,6920.0,2026-04-26,2026-05-11,1122.0,paid,Muthoni,John,April,Sunday,15.0,True,big
2,TXN00660,"Barasa, David",Kajiado,4342.0,2026-02-21,2026-03-05,509.3,paid,Barasa,David,February,Saturday,12.0,True,big
3,TXN00830,"Kimani, Michael",Kisumu,452.0,2026-03-11,2026-04-10,1193.9,paid,Kimani,Michael,March,Wednesday,30.0,False,small
4,TXN00673,"Ochieng, Mary",NaN,829.0,2026-06-09,NaN,694.2,paid,Ochieng,Mary,June,Tuesday,NaN,False,small

---
## 9. What we just did

We moved through the six stages of every data project:

1. **Collect** — `read_csv`
2. **Clean** — names, types, negatives, duplicates, missing values
3. **Transform** — text, dates, split columns, new columns
4. **Explore** — `describe`, `value_counts` *(more tomorrow)*
5. **Analyse** — `groupby` *(Day 4)*
6. **Communicate** — charts *(Day 5)*

Stages 1–3 — the ones we just finished — are **most of the real work**. You can now take a
broken file and hand back a clean one. That is a job.

---
## Your turn — prove it to yourself

Start a **fresh copy** of the raw file and clean it yourself, without scrolling up:

1. Load `kenya_transactions_messy.csv` into a new variable.
2. Fix the column names.
3. Turn `amount` into a real number and null the negatives.
4. Merge the Nairobi spellings.
5. Convert the dates and add a `weekend` column (True on Sat/Sun).
6. Save your result and compare its shape to ours.

If you can do that from memory, you understand data cleaning.

In [ ]:
# your turn — fresh start: