<a href="https://colab.research.google.com/github/jwangui52-web/CDAV/blob/main/Pandas2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import pandas as pd
pd.__version__

'2.2.2'

In [12]:
df=pd.read_csv("/content/kenya_transactions_messy.csv")

In [13]:
df.head()

,Txn ID,Full Name,County,Amount Paid,Txn Date,Paid Date,Rainfall mm,Status
0,TXN00729,"Wanjiku, Jane",NAIROBI,76,22/02/2026,12/03/2026,222.9,?
1,TXN00798,"Onyango, Victor",Kisumu,-,03/06/2026,NaN,902.6,P
2,TXN00672,"Muthoni, John",Kiambu,6920,26/04/2026,11/05/2026,1122.0,P
3,TXN00660,"Barasa, David",Kajiado,4342,21/02/2026,05/03/2026,509.3,P
4,TXN00830,"Kimani, Michael",Kisumu,452,11/03/2026,10/04/2026,1193.9,P

In [14]:
df.tail()

,Txn ID,Full Name,County,Amount Paid,Txn Date,Paid Date,Rainfall mm,Status
995,TXN00248,"Rotich, Stephen",Nairobi,11105,06/06/2026,18/06/2026,896.8,NaN
996,TXN00314,"Auma, Samuel",Mombasa,17377,17/01/2026,NaN,639.9,P
997,TXN00225,"Barasa, David",Kisumu,153,05/04/2026,18/04/2026,1208.0,U
998,TXN00712,"Cheruiyot, Jane",Kericho,4862,09/02/2026,14/02/2026,1636.0,NaN
999,TXN00074,"Nyongesa, Joyce",Nairobi,1021,05/02/2026,15/02/2026,NaN,P

In [15]:
df.shape

(1000, 8)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Txn ID         1000 non-null   object
 1   Full Name      1000 non-null   object
 2   County         993 non-null    object
 3    Amount Paid   960 non-null    object
 4   Txn Date       1000 non-null   object
 5   Paid Date      849 non-null    object
 6   Rainfall mm    963 non-null    float64
 7   Status         879 non-null    object
dtypes: float64(1), object(7)
memory usage: 62.6+ KB

In [17]:
df.describe(include="all")

,Txn ID,Full Name,County,Amount Paid,Txn Date,Paid Date,Rainfall mm,Status
count,1000,1000,993,960,1000,849,963.000000,879
unique,945,663,44,818,184,199,NaN,3
top,TXN00830,"Kimani, Ann",Mombasa,-,16/02/2026,06/05/2026,NaN,P
freq,3,6,119,20,12,12,NaN,438
mean,NaN,NaN,NaN,NaN,NaN,NaN,956.926376,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,439.099355,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,180.800000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,585.650000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,952.400000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,1316.050000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,1747.800000,NaN

In [18]:
df.duplicated().sum()#shows the number of repeated rows.

np.int64(40)

In [19]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997     True
998    False
999    False
Length: 1000, dtype: bool

In [20]:
df[df.duplicated()]

,Txn ID,Full Name,County,Amount Paid,Txn Date,Paid Date,Rainfall mm,Status
161,TXN00750,"Wafula, Mercy",Nakuru,-260,28/01/2026,05/02/2026,1334.8,?
235,TXN00562,"Waweru, Samuel",Kiambu,754,23/06/2026,NaN,NaN,U
263,TXN00855,"Muthoni, Samuel",Kitale,496,04/01/2026,30/01/2026,1747.7,P
286,TXN00001,"Kiptoo, Samuel",Kiambu,608,24/01/2026,NaN,973.4,P
314,TXN00840,"Korir, Alice",Kericho,3805,22/05/2026,26/05/2026,412.8,P
320,TXN00734,"Omondi, Grace",nairobi,4507 KES,05/02/2026,07/03/2026,586.7,P
423,TXN00148,"Muthoni, Paul",nairobi,3042,18/02/2026,21/02/2026,1314.2,NaN
445,TXN00772,"Ochieng, James",BUNGOMA,"3,193 KES",18/05/2026,05/06/2026,781.2,U
473,TXN00660,"Barasa, David",Kajiado,4342,21/02/2026,05/03/2026,509.3,P
497,TXN00418,"Ochieng, Dennis",Kakamega,-,28/05/2026,12/06/2026,1482.4,U
500,TXN00770,"Mwangi, Felix",Meru,2437,11/01/2026,21/01/2026,1161.2,U
506,TXN00517,"Kimani, Ann",Mombasa,96,13/06/2026,NaN,1276.5,NaN
539,TXN00917,"Auma, Grace",Nairobi,131 KES,24/03/2026,30/03/2026,1283.5,P
577,TXN00591,"Atieno, Kevin",Nakuru,793,07/02/2026,19/02/2026,850.6,NaN
593,TXN00705,"Wanjiku, Lucy",Kilifi,391 KES,27/04/2026,28/04/2026,1097.8,U
606,TXN00232,"Muthoni, Lucy",Meru,"4,660",09/02/2026,25/02/2026,803.5,P
616,TXN00111,"Maina, Stephen",NAIROBI,-655,15/01/2026,24/01/2026,1297.5,?
618,TXN00160,"Achieng, Mary",Kisumu,3557,18/05/2026,30/05/2026,1318.0,U
651,TXN00813,"Achieng, Rose",Kitale,300,15/02/2026,NaN,NaN,?
717,TXN00193,"Owino, Purity",Machakos,7079,16/02/2026,11/03/2026,1391.1,P
751,TXN00334,"Rotich, David",Mombasa,798,06/04/2026,16/04/2026,1462.9,U
761,TXN00673,"Ochieng, Mary",NaN,829,09/06/2026,NaN,694.2,P
766,TXN00383,"Njoroge, Ruth",Eldoret,2839,13/04/2026,30/04/2026,232.5,P
782,TXN00915,"Omondi, Alice",Meru,"1,766",03/05/2026,09/05/2026,1634.7,P
783,TXN00830,"Kimani, Michael",Kisumu,2757,11/03/2026,14/03/2026,1193.9,P
788,TXN00508,"Wanjiku, George",Nairobi,3667,12/05/2026,07/06/2026,1376.3,U
797,TXN00109,"Barasa, Peter",Nyeri,429,12/03/2026,28/03/2026,673.6,P
801,TXN00711,"Auma, Eric",Nairobi,-771,12/02/2026,04/03/2026,712.7,?
810,TXN00465,"Waweru, Rose",Nairobi,"18,506",16/04/2026,18/04/2026,1125.3,NaN
859,TXN00857,"Auma, Dennis",NAIROBI,205,06/06/2026,NaN,809.4,U
862,TXN00403,"Ochieng, Ruth",Kiambu,"4,193",08/05/2026,25/05/2026,1493.2,NaN
899,TXN00820,"Njeri, Brian",Mombasa,545,13/03/2026,NaN,504.1,P
901,TXN00768,"Korir, George",Meru,16795,05/04/2026,21/04/2026,1576.6,U
928,TXN00536,"Auma, Beatrice",Nairobi,"19,920",24/03/2026,28/03/2026,1416.2,P
934,TXN00817,"Onyango, Stephen",Kakamega,"1,192",10/03/2026,10/03/2026,762.2,P
939,TXN00656,"Chebet, Ruth",Kitale,266,02/04/2026,22/04/2026,402.5,P
967,TXN00405,"Rotich, Winnie",Kiambu,141,25/04/2026,10/05/2026,503.7,?
973,TXN00938,"Rotich, Brian",Machakos,9352,29/05/2026,03/06/2026,1364.0,P
986,TXN00360,"Ochieng, Ann",KERICHO,1618,17/03/2026,11/04/2026,630.9,U
997,TXN00225,"Barasa, David",Kisumu,153,05/04/2026,18/04/2026,1208.0,U

In [21]:
df.drop_duplicates()

,Txn ID,Full Name,County,Amount Paid,Txn Date,Paid Date,Rainfall mm,Status
0,TXN00729,"Wanjiku, Jane",NAIROBI,76,22/02/2026,12/03/2026,222.9,?
1,TXN00798,"Onyango, Victor",Kisumu,-,03/06/2026,NaN,902.6,P
2,TXN00672,"Muthoni, John",Kiambu,6920,26/04/2026,11/05/2026,1122.0,P
3,TXN00660,"Barasa, David",Kajiado,4342,21/02/2026,05/03/2026,509.3,P
4,TXN00830,"Kimani, Michael",Kisumu,452,11/03/2026,10/04/2026,1193.9,P
...,...,...,...,...,...,...,...,...
994,TXN00774,"Mutua, Ruth",Nairobi,562,05/01/2026,17/01/2026,737.3,NaN
995,TXN00248,"Rotich, Stephen",Nairobi,11105,06/06/2026,18/06/2026,896.8,NaN
996,TXN00314,"Auma, Samuel",Mombasa,17377,17/01/2026,NaN,639.9,P
998,TXN00712,"Cheruiyot, Jane",Kericho,4862,09/02/2026,14/02/2026,1636.0,NaN
999,TXN00074,"Nyongesa, Joyce",Nairobi,1021,05/02/2026,15/02/2026,NaN,P

In [22]:
df.isna().sum()

Txn ID             0
Full Name          0
County             7
 Amount Paid      40
Txn Date           0
Paid Date        151
Rainfall mm       37
Status           121
dtype: int64

In [23]:
df.columns = df.columns.str.strip()
df[df["Amount Paid"].isna()]

,Txn ID,Full Name,County,Amount Paid,Txn Date,Paid Date,Rainfall mm,Status
15,TXN00054,"Kariuki, Nancy",Nakuru,NaN,09/03/2026,02/04/2026,874.0,P
70,TXN00708,"Wafula, Stephen",Kitale,NaN,27/02/2026,20/03/2026,983.1,?
89,TXN00607,"Odhiambo, Eric",Eldoret,NaN,26/04/2026,19/05/2026,NaN,U
91,TXN00105,"Wanjiku, Michael",Mombasa,NaN,26/01/2026,06/02/2026,255.1,?
111,TXN00881,"Rotich, Grace",Mombasa,NaN,17/01/2026,NaN,660.8,NaN
116,TXN00822,"Onyango, Eric",Kisumu,NaN,13/01/2026,20/01/2026,1340.9,?
118,TXN00407,"Auma, Anthony",Nairobi,NaN,04/05/2026,25/05/2026,1611.0,U
152,TXN00761,"Wafula, Faith",Kiambu,NaN,27/02/2026,03/03/2026,1103.5,U
160,TXN00668,"Korir, Brian",Meru,NaN,30/06/2026,19/07/2026,1625.3,P
166,TXN00084,"Muthoni, Winnie",Kakamega,NaN,12/01/2026,18/01/2026,1379.7,P
233,TXN00724,"Nyongesa, Anthony",Nairobi​,NaN,25/06/2026,NaN,248.6,P
241,TXN00152,"Waweru, Felix",Nakuru,NaN,20/01/2026,29/01/2026,NaN,NaN
249,TXN00547,"Odhiambo, Nancy",Kiambu,NaN,11/03/2026,15/03/2026,1741.0,U
356,TXN00936,"Omondi, Beatrice",Bungoma,NaN,08/03/2026,07/04/2026,1546.7,U
372,TXN00525,"Atieno, Dennis",Nakuru,NaN,25/05/2026,22/06/2026,219.8,?
381,TXN00307,"Mutua, Rose",Meru,NaN,27/04/2026,18/05/2026,492.4,U
385,TXN00943,"Odhiambo, Sarah",Nairobi,NaN,07/03/2026,15/03/2026,1643.6,NaN
489,TXN00297,"Chebet, Lucy",Mombasa,NaN,30/05/2026,02/06/2026,970.0,P
490,TXN00223,"Kariuki, Stephen",Machakos,NaN,05/05/2026,18/05/2026,1471.4,P
512,TXN00277,"Muthoni, Esther",Mombasa,NaN,11/04/2026,03/05/2026,864.7,NaN
537,TXN00601,"Owino, Brian",Machakos,NaN,22/05/2026,30/05/2026,352.7,U
554,TXN00448,"Achieng, Paul",Nairobi,NaN,14/01/2026,07/02/2026,1288.5,U
555,TXN00488,"Mutua, Caroline",Machakos,NaN,16/04/2026,29/04/2026,1512.3,?
580,TXN00655,"Wambui, Winnie",NAIROBI,NaN,03/03/2026,07/03/2026,682.7,P
603,TXN00556,"Maina, Stephen",Nakuru,NaN,18/01/2026,21/01/2026,793.6,P
631,TXN00632,"Njeri, Stephen",Meru,NaN,03/06/2026,20/06/2026,1475.1,P
650,TXN00335,"Atieno, John",Bungoma,NaN,28/01/2026,07/02/2026,526.7,P
672,TXN00295,"Njoroge, Winnie",Kajiado,NaN,31/01/2026,22/02/2026,446.1,P
699,TXN00231,"Auma, Dennis",nairobi,NaN,25/05/2026,NaN,1196.4,U
710,TXN00070,"Omondi, Alice",Mombasa,NaN,08/05/2026,23/05/2026,548.6,U
727,TXN00783,"Kamau, Caroline",Nyeri,NaN,21/02/2026,01/03/2026,675.4,P
740,TXN00682,"Omondi, Mercy",Kisumu,NaN,15/06/2026,NaN,1532.4,?
776,TXN00811,"Onyango, Caroline",Kiambu,NaN,14/06/2026,04/07/2026,982.8,P
868,TXN00459,"Wanjiku, Winnie",Mombasa,NaN,06/05/2026,11/05/2026,1212.2,P
877,TXN00519,"Maina, Samuel",Nakuru,NaN,11/05/2026,08/06/2026,947.7,U
952,TXN00604,"Korir, Beatrice",Mombasa,NaN,22/06/2026,13/07/2026,774.7,?
969,TXN00122,"Onyango, Beatrice",NAIROBI,NaN,13/01/2026,NaN,923.8,U
987,TXN00099,"Wanjiku, Nancy",Meru,NaN,30/03/2026,19/04/2026,409.3,P
989,TXN00555,"Omondi, Alice",NAIROBI,NaN,15/01/2026,19/01/2026,1355.4,U
990,TXN00215,"Kiptoo, Daniel",Kajiado,NaN,11/02/2026,13/02/2026,1415.6,?

In [24]:
df.isnull().sum()

Txn ID           0
Full Name        0
County           7
Amount Paid     40
Txn Date         0
Paid Date      151
Rainfall mm     37
Status         121
dtype: int64

In [25]:
df['Amount Paid'] = df["Amount Paid"].fillna(0)

In [26]:
df.isnull().sum()

Txn ID           0
Full Name        0
County           7
Amount Paid      0
Txn Date         0
Paid Date      151
Rainfall mm     37
Status         121
dtype: int64

In [27]:
missing=pd.DataFrame({
    'missing_count': df.isnull().sum(),
    'missing_pct': (df.isnull().sum()/len(df)*100).round(1)
})
missing

             missing_count  missing_pct
Txn ID                   0          0.0
Full Name                0          0.0
County                   7          0.7
Amount Paid              0          0.0
Txn Date                 0          0.0
Paid Date              151         15.1
Rainfall mm             37          3.7
Status                 121         12.1

In [28]:
#Before-note some spaces around some names
print('Before:',df.columns.tolist())

Before: ['Txn ID', 'Full Name', 'County', 'Amount Paid', 'Txn Date', 'Paid Date', 'Rainfall mm', 'Status']

In [30]:
df.columns=(
    df.columns.str.strip()    #remove leading /trailing spaces
    .str.lower()              #make everything lowercase
    .str.replace(' ','_')     #spaces inside names become underscores
)

In [31]:
#verify
print('After:',df.columns.tolist())

After: ['txn_id', 'full_name', 'county', 'amount_paid', 'txn_date', 'paid_date', 'rainfall_mm', 'status']

In [39]:
print('Total rows:    ', len(df))
print('Duplicate txn_id rows:',df.duplicated('txn_id'))

Total rows:          1000
Duplicate txn_id rows: 0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997     True
998    False
999    False
Length: 1000, dtype: bool

In [ ]:
#clean the county column
print('unique counties BEFORE cleaning')