<a href="https://colab.research.google.com/github/jwangui52-web/CDAV/blob/main/pandas_day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#most streamed artist on spotify.

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
pd.__version__

'2.2.2'

In [ ]:
df=pd.read_excel("/content/Most Streamed Artists on Spotify (17_07_2026).csv.xlsx")
df.head()

,Artist,Sex,Country,Langugage,Primary Genre,Artist Type,Total Streams (in millions),Lead Streams (in millions),Feature Streams (in millions),Solo Streams (in millions)
0,Drake,Male,Canada,English,Hip-Hop,Solo,137492.1,94851.1,42640.9,53323.9
1,Taylor Swift,Female,United States,English,Pop,Solo,127861.0,126177.3,1683.8,113421.5
2,Bad Bunny,Male,United States,Spanish,Reggaeton,Solo,125899.8,82189.3,43710.5,48887.0
3,The Weeknd,Male,Canada,English,R&B,Solo,95703.2,77189.4,18513.8,51020.0
4,Justin Bieber,Male,Canada,English,Pop,Solo,78104.4,48316.2,29788.2,29638.3

In [ ]:
df.tail()

,Artist,Sex,Country,Langugage,Primary Genre,Artist Type,Total Streams (in millions),Lead Streams (in millions),Feature Streams (in millions),Solo Streams (in millions)
495,The Cure,Male,United Kingdom,English,Rock,Group,7034.1,7035.0,3.3,6940.1
496,The MarÃ­as,Mixed,United States,English,Pop,Group,7029.1,5774.4,1261.4,5705.9
497,Limp Bizkit,Male,United States,English,Nu Metal,Group,7018.9,7018.4,5.4,6806.0
498,Korn,Male,United States,English,Metal,Group,6976.4,4188.4,2798.5,6414.9
499,Omar Courtz,Male,United States,Spanish,Reggaeton,Solo,6972.0,6956.0,20.3,1876.2

In [ ]:
df.head(10)

,Artist,Sex,Country,Langugage,Primary Genre,Artist Type,Total Streams (in millions),Lead Streams (in millions),Feature Streams (in millions),Solo Streams (in millions)
0,Drake,Male,Canada,English,Hip-Hop,Solo,137492.1,94851.1,42640.9,53323.9
1,Taylor Swift,Female,United States,English,Pop,Solo,127861.0,126177.3,1683.8,113421.5
2,Bad Bunny,Male,United States,Spanish,Reggaeton,Solo,125899.8,82189.3,43710.5,48887.0
3,The Weeknd,Male,Canada,English,R&B,Solo,95703.2,77189.4,18513.8,51020.0
4,Justin Bieber,Male,Canada,English,Pop,Solo,78104.4,48316.2,29788.2,29638.3
5,Ariana Grande,Female,United States,English,Pop,Solo,68298.9,57097.5,11201.4,41615.5
6,Travis Scott,Male,United States,English,Hip-Hop,Solo,65349.7,35338.7,30027.0,25309.9
7,Kanye West,Male,United States,English,Hip-Hop,Solo,65142.9,46558.4,18584.5,28473.0
8,Ed Sheeran,Male,United Kingdom,English,Pop,Solo,64656.9,57704.0,6967.8,46700.0
9,Eminem,Male,United States,English,Hip-Hop,Solo,64549.0,54466.8,10100.7,32940.0

In [ ]:
df.tail(12)

,Artist,Sex,Country,Langugage,Primary Genre,Artist Type,Total Streams (in millions),Lead Streams (in millions),Feature Streams (in millions),Solo Streams (in millions)
488,Grupo Marca Registrada,Male,Mexico,Spanish,Regional Mexican,Group,7123.4,5595.9,1527.5,3002.0
489,benny blanco,Male,United States,English,Pop,Solo,7114.1,4400.3,2716.0,3.9
490,JID,Male,United States,English,Hip-Hop,Solo,7073.7,2882.3,4191.4,1158.3
491,YNW Melly,Male,United States,English,Hip-Hop,Solo,7061.3,7067.3,NaN,4346.8
492,Juan Gabriel,Male,Mexico,Spanish,Latin,Solo,7059.2,6505.8,557.1,5676.3
493,Los Temerarios,Male,Mexico,Spanish,Latin,Group,7059.2,6607.2,446.9,7059.2
494,Jason Mraz,Male,United States,English,Pop,Solo,7048.5,6851.4,199.1,5805.0
495,The Cure,Male,United Kingdom,English,Rock,Group,7034.1,7035.0,3.3,6940.1
496,The MarÃ­as,Mixed,United States,English,Pop,Group,7029.1,5774.4,1261.4,5705.9
497,Limp Bizkit,Male,United States,English,Nu Metal,Group,7018.9,7018.4,5.4,6806.0
498,Korn,Male,United States,English,Metal,Group,6976.4,4188.4,2798.5,6414.9
499,Omar Courtz,Male,United States,Spanish,Reggaeton,Solo,6972.0,6956.0,20.3,1876.2

In [ ]:
df.shape

(500, 10)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Artist                         500 non-null    object
 1   Sex                            500 non-null    object
 2   Country                        500 non-null    object
 3   Langugage                      500 non-null    object
 4   Primary Genre                  500 non-null    object
 5    Artist Type                   500 non-null    object
 6   Total Streams (in millions)    500 non-null    float64
 7   Lead Streams (in millions)     497 non-null    float64
 8   Feature Streams (in millions)  468 non-null    float64
 9   Solo Streams (in millions)     493 non-null    float64
dtypes: float64(4), object(6)
memory usage: 39.2+ KB

In [ ]:
df.describe()

,Total Streams (in millions),Lead Streams (in millions),Feature Streams (in millions),Solo Streams (in millions)
count,500.000000,497.000000,468.000000,493.000000
mean,16817.610200,12215.024145,5001.377137,8442.593915
std,14845.197632,11842.628550,6021.629551,9605.072797
min,6972.000000,8.400000,0.400000,1.300000
25%,8768.175000,6568.500000,971.450000,2755.300000
50%,11923.250000,8772.200000,3367.850000,6592.700000
75%,18020.050000,13579.300000,6333.525000,10141.500000
max,137492.100000,126177.300000,43710.500000,113421.500000

In [ ]:
df.columns

Index(['Artist', 'Sex', 'Country', 'Langugage', 'Primary Genre',
       ' Artist Type', 'Total Streams (in millions)',
       'Lead Streams (in millions)', 'Feature Streams (in millions)',
       'Solo Streams (in millions)'],
      dtype='object')

In [ ]:
df.dtypes

Artist                            object
Sex                               object
Country                           object
Langugage                         object
Primary Genre                     object
 Artist Type                      object
Total Streams (in millions)      float64
Lead Streams (in millions)       float64
Feature Streams (in millions)    float64
Solo Streams (in millions)       float64
dtype: object

In [ ]:
df.index

RangeIndex(start=0, stop=500, step=1)

In [ ]:
df.size

5000

In [ ]:
df["Sex"].unique()

array(['Male', 'Female', 'Mixed'], dtype=object)

In [ ]:
df["Sex"].nunique()

3

In [ ]:
df["Country"].unique()

array(['Canada', 'United States', 'United Kingdom', 'Barbados',
       'Colombia', 'South Korea', 'Trinidad and Tobago', 'France',
       'India', 'Scotland', 'Mexico', 'Australia', 'Germany', 'Cuba',
       'Sweden', 'Norway', 'Panama', 'Brazil', 'Netherlands', 'Jamaica',
       'Senegal', 'Ireland', 'Argentina', 'Spain', 'Japan', 'New Zealand',
       'Morocco', 'Chile', 'Russia', 'Nigeria', 'South Africa',
       'Venezuela', 'Italy', 'Dominican Republic', 'Belgium', 'DR Congo',
       'Nepal', 'Pakistan', 'Guatemala', 'Austria', 'Philippines',
       'Denmark', 'Iceland'], dtype=object)

In [ ]:
df["Language"]
df[("Language","Country")]

KeyError: 'Language'

In [ ]:
df.loc[2,"Sex"]

'Male'

In [ ]:
df.iloc[2,0]

'Bad Bunny'

In [ ]:
df.loc[2,"Country"]

'United States'

In [ ]:
df.iloc[2,0]

'Bad Bunny'

In [ ]:
df.loc[0]

Artist                              Drake
Sex                                  Male
Country                            Canada
Langugage                         English
Primary Genre                     Hip-Hop
 Artist Type                         Solo
Total Streams (in millions)      137492.1
Lead Streams (in millions)        94851.1
Feature Streams (in millions)     42640.9
Solo Streams (in millions)        53323.9
Name: 0, dtype: object

In [ ]:
import pandas as pd
pd.options.display.max_rows

60

In [ ]:
import pandas as pd
data={
  "calories":[420,30,390],
  "duration":[50,40,45]
  }
myvar=pd.DataFrame(data)
print(myvar)

   calories  duration
0       420        50
1        30        40
2       390        45

In [ ]:
import pandas as pd
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Artist                         500 non-null    object
 1   Sex                            500 non-null    object
 2   Country                        500 non-null    object
 3   Langugage                      500 non-null    object
 4   Primary Genre                  500 non-null    object
 5    Artist Type                   500 non-null    object
 6   Total Streams (in millions)    500 non-null    float64
 7   Lead Streams (in millions)     497 non-null    float64
 8   Feature Streams (in millions)  468 non-null    float64
 9   Solo Streams (in millions)     493 non-null    float64
dtypes: float64(4), object(6)
memory usage: 39.2+ KB

In [ ]:
df["Langugage"]=="English"

0       True
1       True
2      False
3       True
4       True
       ...
495     True
496     True
497     True
498     True
499    False
Name: Langugage, Length: 500, dtype: bool

In [ ]:
df["Langugage"]!="English"
#everything except English.

0      False
1      False
2       True
3      False
4      False
       ...
495    False
496    False
497    False
498    False
499     True
Name: Langugage, Length: 500, dtype: bool

In [ ]:
df[df["Lead Streams (in millions)"]>10000]

,Artist,Sex,Country,Langugage,Primary Genre,Artist Type,Total Streams (in millions),Lead Streams (in millions),Feature Streams (in millions),Solo Streams (in millions)
0,Drake,Male,Canada,English,Hip-Hop,Solo,137492.1,94851.1,42640.9,53323.9
1,Taylor Swift,Female,United States,English,Pop,Solo,127861.0,126177.3,1683.8,113421.5
2,Bad Bunny,Male,United States,Spanish,Reggaeton,Solo,125899.8,82189.3,43710.5,48887.0
3,The Weeknd,Male,Canada,English,R&B,Solo,95703.2,77189.4,18513.8,51020.0
4,Justin Bieber,Male,Canada,English,Pop,Solo,78104.4,48316.2,29788.2,29638.3
...,...,...,...,...,...,...,...,...,...,...
298,Foo Fighters,Male,United States,English,Rock,Group,10571.1,10570.2,4.5,10555.6
299,The 1975,Male,United Kingdom,English,Rock,Group,10489.6,10191.7,301.5,10165.9
305,Conan Gray,Male,United States,English,Pop,Solo,10313.5,10145.1,172.0,10141.5
310,My Chemical Romance,Male,United States,English,Rock,Group,10180.2,10185.8,NaN,10132.8
314,La Arrolladora Banda El LimÃ³n De Rene Camacho,Male,Mexico,Spanish,Regional Mexican,Group,10147.9,10065.9,89.1,9956.8

In [ ]:
is_United_States=df["Country"]=="United States"
is_viewed=df["Lead Streams (in millions)"]>10000
df[is_United_States & is_viewed]

,Artist,Sex,Country,Langugage,Primary Genre,Artist Type,Total Streams (in millions),Lead Streams (in millions),Feature Streams (in millions),Solo Streams (in millions)
1,Taylor Swift,Female,United States,English,Pop,Solo,127861.0,126177.3,1683.8,113421.5
2,Bad Bunny,Male,United States,Spanish,Reggaeton,Solo,125899.8,82189.3,43710.5,48887.0
5,Ariana Grande,Female,United States,English,Pop,Solo,68298.9,57097.5,11201.4,41615.5
6,Travis Scott,Male,United States,English,Hip-Hop,Solo,65349.7,35338.7,30027.0,25309.9
7,Kanye West,Male,United States,English,Hip-Hop,Solo,65142.9,46558.4,18584.5,28473.0
...,...,...,...,...,...,...,...,...,...,...
290,blink-182,Male,United States,English,Rock,Group,10760.4,10630.4,133.8,10584.7
297,Aventura,Male,United States,Spanish,Bachata,Group,10607.0,10520.3,92.7,8371.3
298,Foo Fighters,Male,United States,English,Rock,Group,10571.1,10570.2,4.5,10555.6
305,Conan Gray,Male,United States,English,Pop,Solo,10313.5,10145.1,172.0,10141.5
310,My Chemical Romance,Male,United States,English,Rock,Group,10180.2,10185.8,NaN,10132.8

In [ ]:

len(is_United_States)

500

In [ ]:
is_United_States.shape

(500,)

In [ ]:
is_United_States=df["Country"]=="United States"
is_viewed=df["Lead Streams (in millions)"]>10000
df[is_United_States | is_viewed]

,Artist,Sex,Country,Langugage,Primary Genre,Artist Type,Total Streams (in millions),Lead Streams (in millions),Feature Streams (in millions),Solo Streams (in millions)
0,Drake,Male,Canada,English,Hip-Hop,Solo,137492.1,94851.1,42640.9,53323.9
1,Taylor Swift,Female,United States,English,Pop,Solo,127861.0,126177.3,1683.8,113421.5
2,Bad Bunny,Male,United States,Spanish,Reggaeton,Solo,125899.8,82189.3,43710.5,48887.0
3,The Weeknd,Male,Canada,English,R&B,Solo,95703.2,77189.4,18513.8,51020.0
4,Justin Bieber,Male,Canada,English,Pop,Solo,78104.4,48316.2,29788.2,29638.3
...,...,...,...,...,...,...,...,...,...,...
494,Jason Mraz,Male,United States,English,Pop,Solo,7048.5,6851.4,199.1,5805.0
496,The MarÃ­as,Mixed,United States,English,Pop,Group,7029.1,5774.4,1261.4,5705.9
497,Limp Bizkit,Male,United States,English,Nu Metal,Group,7018.9,7018.4,5.4,6806.0
498,Korn,Male,United States,English,Metal,Group,6976.4,4188.4,2798.5,6414.9
499,Omar Courtz,Male,United States,Spanish,Reggaeton,Solo,6972.0,6956.0,20.3,1876.2

In [ ]:
df[~(df["Primary Genre"]=="R&B")]

,Artist,Sex,Country,Langugage,Primary Genre,Artist Type,Total Streams (in millions),Lead Streams (in millions),Feature Streams (in millions),Solo Streams (in millions)
0,Drake,Male,Canada,English,Hip-Hop,Solo,137492.1,94851.1,42640.9,53323.9
1,Taylor Swift,Female,United States,English,Pop,Solo,127861.0,126177.3,1683.8,113421.5
2,Bad Bunny,Male,United States,Spanish,Reggaeton,Solo,125899.8,82189.3,43710.5,48887.0
4,Justin Bieber,Male,Canada,English,Pop,Solo,78104.4,48316.2,29788.2,29638.3
5,Ariana Grande,Female,United States,English,Pop,Solo,68298.9,57097.5,11201.4,41615.5
...,...,...,...,...,...,...,...,...,...,...
495,The Cure,Male,United Kingdom,English,Rock,Group,7034.1,7035.0,3.3,6940.1
496,The MarÃ­as,Mixed,United States,English,Pop,Group,7029.1,5774.4,1261.4,5705.9
497,Limp Bizkit,Male,United States,English,Nu Metal,Group,7018.9,7018.4,5.4,6806.0
498,Korn,Male,United States,English,Metal,Group,6976.4,4188.4,2798.5,6414.9
499,Omar Courtz,Male,United States,Spanish,Reggaeton,Solo,6972.0,6956.0,20.3,1876.2

In [ ]:
#between-inclusive at both ends
df[df["Lead Streams (in millions)"].between (50000,100000)]

,Artist,Sex,Country,Langugage,Primary Genre,Artist Type,Total Streams (in millions),Lead Streams (in millions),Feature Streams (in millions),Solo Streams (in millions)
0,Drake,Male,Canada,English,Hip-Hop,Solo,137492.1,94851.1,42640.9,53323.9
2,Bad Bunny,Male,United States,Spanish,Reggaeton,Solo,125899.8,82189.3,43710.5,48887.0
3,The Weeknd,Male,Canada,English,R&B,Solo,95703.2,77189.4,18513.8,51020.0
5,Ariana Grande,Female,United States,English,Pop,Solo,68298.9,57097.5,11201.4,41615.5
8,Ed Sheeran,Male,United Kingdom,English,Pop,Solo,64656.9,57704.0,6967.8,46700.0
9,Eminem,Male,United States,English,Hip-Hop,Solo,64549.0,54466.8,10100.7,32940.0
11,Billie Eilish,Female,United States,English,Pop,Solo,58049.5,57160.1,889.4,51567.9

In [ ]:
df.query("`Primary Genre` == 'R&B' and `Lead Streams (in millions)` > 10000")

,Artist,Sex,Country,Langugage,Primary Genre,Artist Type,Total Streams (in millions),Lead Streams (in millions),Feature Streams (in millions),Solo Streams (in millions)
3,The Weeknd,Male,Canada,English,R&B,Solo,95703.2,77189.4,18513.8,51020.0
21,Chris Brown,Male,United States,English,R&B,Solo,43963.8,24455.7,19523.9,12219.3
33,SZA,Female,United States,English,R&B,Solo,38879.6,25267.5,13627.2,19804.6
39,Khalid,Male,United States,English,R&B,Solo,35727.2,18499.9,17234.4,12520.6
80,Frank Ocean,Male,United States,English,R&B,Solo,24807.4,20425.4,4391.5,18809.3
119,USHER,Male,United States,English,R&B,Solo,18413.2,12525.4,5896.3,5222.1
125,Kali Uchis,Female,Colombia,English,R&B,Solo,18005.3,10367.0,7646.6,7259.1
154,Daniel Caesar,Male,Canada,English,R&B,Solo,15876.2,12905.1,2982.4,7353.2
178,Joji,Male,Japan,English,R&B,Solo,14512.1,13579.3,938.4,12111.7
180,PARTYNEXTDOOR,Male,Canada,English,R&B,Solo,14506.3,13237.2,1275.0,7177.2
198,Bryson Tiller,Male,United States,English,R&B,Solo,13890.6,13739.5,155.6,8915.5

In [ ]:
df["Primary Genre"].value_counts()

Primary Genre
Hip-Hop             115
Pop                 102
Rock                 60
Reggaeton            43
R&B                  31
Latin                30
EDM                  22
Regional Mexican     19
K-Pop                11
Filmi                11
Country              10
Alternative           9
Sertanjeo             9
Metal                 8
Folk                  4
Soundtrack            3
Bachata               3
Soul                  3
Reggae                2
Afrobeats             2
Spoken Word           1
Children's Music      1
Nu Metal              1
Name: count, dtype: int64

In [ ]:
df["Primary Genre"].value_counts(dropna=False)#missing values

Primary Genre
Hip-Hop             115
Pop                 102
Rock                 60
Reggaeton            43
R&B                  31
Latin                30
EDM                  22
Regional Mexican     19
K-Pop                11
Filmi                11
Country              10
Alternative           9
Sertanjeo             9
Metal                 8
Folk                  4
Soundtrack            3
Bachata               3
Soul                  3
Reggae                2
Afrobeats             2
Spoken Word           1
Children's Music      1
Nu Metal              1
Name: count, dtype: int64

In [ ]:
df["Primary Genre"].unique()

array(['Hip-Hop', 'Pop', 'Reggaeton', 'R&B', 'K-Pop', 'Rock',
       'Alternative', 'EDM', 'Filmi', 'Latin', 'Regional Mexican',
       'Country', 'Spoken Word', 'Soundtrack', 'Bachata', 'Sertanjeo',
       'Reggae', 'Folk', 'Metal', 'Afrobeats', 'Soul', "Children's Music",
       'Nu Metal'], dtype=object)

In [ ]:
df["Primary Genre"].nunique()

23

Data cleaning

In [ ]:
df.isna()#True where a value is missing

,Artist,Sex,Country,Langugage,Primary Genre,Artist Type,Total Streams (in millions),Lead Streams (in millions),Feature Streams (in millions),Solo Streams (in millions)
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
495,False,False,False,False,False,False,False,False,False,False
496,False,False,False,False,False,False,False,False,False,False
497,False,False,False,False,False,False,False,False,False,False
498,False,False,False,False,False,False,False,False,False,False
499,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isna().sum()

Artist                            0
Sex                               0
Country                           0
Langugage                         0
Primary Genre                     0
 Artist Type                      0
Total Streams (in millions)       0
Lead Streams (in millions)        3
Feature Streams (in millions)    32
Solo Streams (in millions)        7
dtype: int64

In [ ]:
df.isna().sum().sum()#total across the whole table

np.int64(42)

In [ ]:
df.isna().mean()*100  #percentage missing per column

Artist                           0.0
Sex                              0.0
Country                          0.0
Langugage                        0.0
Primary Genre                    0.0
 Artist Type                     0.0
Total Streams (in millions)      0.0
Lead Streams (in millions)       0.6
Feature Streams (in millions)    6.4
Solo Streams (in millions)       1.4
dtype: float64

In [ ]:
df.dropna()

,Artist,Sex,Country,Langugage,Primary Genre,Artist Type,Total Streams (in millions),Lead Streams (in millions),Feature Streams (in millions),Solo Streams (in millions)
0,Drake,Male,Canada,English,Hip-Hop,Solo,137492.1,94851.1,42640.9,53323.9
1,Taylor Swift,Female,United States,English,Pop,Solo,127861.0,126177.3,1683.8,113421.5
2,Bad Bunny,Male,United States,Spanish,Reggaeton,Solo,125899.8,82189.3,43710.5,48887.0
3,The Weeknd,Male,Canada,English,R&B,Solo,95703.2,77189.4,18513.8,51020.0
4,Justin Bieber,Male,Canada,English,Pop,Solo,78104.4,48316.2,29788.2,29638.3
...,...,...,...,...,...,...,...,...,...,...
495,The Cure,Male,United Kingdom,English,Rock,Group,7034.1,7035.0,3.3,6940.1
496,The MarÃ­as,Mixed,United States,English,Pop,Group,7029.1,5774.4,1261.4,5705.9
497,Limp Bizkit,Male,United States,English,Nu Metal,Group,7018.9,7018.4,5.4,6806.0
498,Korn,Male,United States,English,Metal,Group,6976.4,4188.4,2798.5,6414.9
499,Omar Courtz,Male,United States,Spanish,Reggaeton,Solo,6972.0,6956.0,20.3,1876.2

In [ ]:
df["Country"].fillna(0)

0              Canada
1       United States
2       United States
3              Canada
4              Canada
            ...
495    United Kingdom
496     United States
497     United States
498     United States
499     United States
Name: Country, Length: 500, dtype: object

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df[df.duplicated()]

Empty DataFrame
Columns: [Artist, Sex, Country, Langugage, Primary Genre,  Artist Type, Total Streams (in millions), Lead Streams (in millions), Feature Streams (in millions), Solo Streams (in millions)]
Index: []

In [ ]:
import pandas as pd
df = df.rename(columns={"Langugage":"Language"})

NameError: name 'df' is not defined

In [ ]:
import pandas as pd
s=pd.Series(["60670.7","58049.5","N/A","56459.5"])
pd.to_numeric(s,errors="coerce")

0    60670.7
1    58049.5
2        NaN
3    56459.5
dtype: float64

In [ ]:
df.describe()

NameError: name 'df' is not defined