<a href="https://colab.research.google.com/github/jwangui52-web/CDAV/blob/main/stats1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
import pandas as pd
import numpy as np

In [34]:
df=pd.read_csv("/content/student_performance.csv")

In [35]:
df.head(11)

,StudentID,Name,Gender,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,ParentalSupport,FinalGrade
0,1,John,Male,85,15,78,1,High,80
1,2,Sarah,Female,90,20,85,2,Medium,87
2,3,Alex,Male,78,10,65,0,Low,68
3,4,Michael,Male,92,25,90,3,High,92
4,5,Emma,Female,88,18,82,2,Medium,85
5,6,Olivia,Female,95,30,88,1,High,90
6,7,Daniel,Male,70,8,60,0,Low,62
7,8,Sophia,Female,85,17,77,1,Medium,78
8,9,James,Male,82,12,70,2,Low,72
9,10,Isabella,Female,91,22,86,3,High,88

In [36]:
grade=df["FinalGrade"]
print(grade)

0    80
1    87
2    68
3    92
4    85
5    90
6    62
7    78
8    72
9    88
Name: FinalGrade, dtype: int64

In [48]:
grade.mean()

np.float64(80.2)

In [49]:
grade.mode()

0    62
1    68
2    72
3    78
4    80
5    85
6    87
7    88
8    90
9    92
Name: FinalGrade, dtype: int64

#no mode

In [37]:
#Quantiles.....>Q1,Q2,Q3
print(f"Q1: {grade.quantile(0.25)}")
print(f"Q2: {grade.quantile(0.50)}")
print(f"Q3: {grade.quantile(0.75)}")

Q1: 73.5
Q2: 82.5
Q3: 87.75

In [38]:
#Deciles
print(f"D1: {grade.quantile(0.10)}")
print(f"D2: {grade.quantile(0.50)}")
print(f"D3: {grade.quantile(0.30)}")

D1: 67.4
D2: 82.5
D3: 76.2

In [39]:
#percentiles
print(f"Q1: {grade.quantile(0.01)}")
print(f"Q2: {grade.quantile(0.50)}")
print(f"Q3: {grade.quantile(0.30)}")

Q1: 62.54
Q2: 82.5
Q3: 76.2

In [47]:
#range
maximum=grade.max()
minimum=grade.min()
grade_range=maximum-minimum
grade_range

30

In [46]:
Q3=grade.quantile(0.75)
Q1=grade.quantile(0.25)
IQR=Q3-Q1
IQR

np.float64(14.25)

In [41]:
#variance and std
var=grade.var()
std=grade.std()
var

101.95555555555555

In [45]:
std

10.09730437074943

In [43]:
grade.describe()

count    10.000000
mean     80.200000
std      10.097304
min      62.000000
25%      73.500000
50%      82.500000
75%      87.750000
max      92.000000
Name: FinalGrade, dtype: float64

In [44]:
grade.describe(percentiles=[0.10,0.20,0.25])

count    10.000000
mean     80.200000
std      10.097304
min      62.000000
10%      67.400000
20%      71.200000
25%      73.500000
50%      82.500000
max      92.000000
Name: FinalGrade, dtype: float64